### ISSUE TITLE
[feature] Add Dolby vision to HDR10+ conversion

### ISSUE THREAD

**Issue by cromefire** [quietvoid/hdr10plus_tool#37]
As dovi_tool now supports HDR10+ JSON to RPU conversation, but the other way around would be a great feature to. In the best case scenario it's just the same mapping reversed, worst case it's non reversible, so this feature wouldn't be possible to implement.

This feature could be very useful for some people I guess because:

- There are some TVs (namely Samsung) and many phones (Android) that only have HDR10+ and no DV
- (MKV) DV support is still rather lacking in many cases, my TV for example just doesn't parse DV from it and Kodi also has quite some difficulties and still crashes in many cases (probably due to the dependency on hardware) with DV support, HDR10+ support on the other hand seems great, both Kodi and the TV accept an MKV with HDR10+ just fine with no problems at all.
- Codec support: if you want to transcode DV stuff into VP9 you can't use DV, but you can use HDR10+ just fine, but probably rather niche and ffmpeg support is also still not working as well as it should, transcoding HDR10+ hevc to VP9 is basically not a thing right now.

**Comment by quietvoid** [comment]
> Regarding Dolby's tonemap, how did you solve the problem for the HDR10+ to DV conversion?

The HDR10+ to Dolby Vision conversion is simply adding L1 metadata, which is the min/max/avg brightness of a shot.
That data is already present in HDR10+ metadata, on a different scale (0 to 100 000 instead of 0 to 4095).

Proper HDR10+ requires a Bezier curve to adjust the mapping for the target display, and there's no public algorithm for generating it.

And Dolby specifies multiple parameters to adjust the tonemapping, which can't be directly translated.
And I don't know how HDR10+ displays would react with bogus data, because I don't own one.

This isn't something I'm willing to invest time into, because I have no way to test for myself.

**Comment by cromefire** [comment]
Okay, thanks for the insight

**Comment by ValZapod** [comment]
> That is true and a thing that probably only time will solve

There is actualy HDR10+ sample in AV1 there.

> * (MKV) DV support is still rather lacking in many cases,

Just like EAC3 mp4 is better. Morover it is a good idea to use mp4v2.

**Comment by cromefire** [comment]
> Just like EAC3 mp4 is better. Morover it is a good idea to use mp4v2.

Well some of the features and support (not to mention tooling) are just not available on mp4 and also turns out just the problems are with the DV decoder of the mediatek chipset (of my CCwGT) and not MKV (although the TV itself for example seems to only be able to play DV from m2ts). But that's not the core problem of this issue.
