### ISSUE TITLE
Decode vs display order

### ISSUE THREAD

**Issue by Audionut** [quietvoid/hdr10plus_tool#56]
https://github.com/quietvoid/hdr10plus_tool/commit/545038f22e055c9874b8137336a17777c0007ca3

A decoder that decodes frames in display order, but seemingly decodes corresponding metadata in _some other order_, sounds like a broken decoder.

**Comment by quietvoid** [comment]
The metadata is in the same order as the frames. Every HDR10+ metadata SEI is attached to the right frame.
The issue is how the original metadata was inserted into the bitstream, not how it is parsed/decoded at playback.

**Comment by Audionut** [comment]
It makes no sense, whatsoever, that "misauthored HEVC files" don't need to be touched by your "re-ordering" code, but "correctly" authored HEVC streams need to have their metadata "re-ordered" by your code.

**Comment by quietvoid** [comment]
> It makes no sense, whatsoever, that "misauthored HEVC files" don't need to be touched by your "re-ordering" code, but "correctly" authored HEVC streams need to have their metadata "re-ordered" by your code.

You misunderstand how the parsing works and why reordering is necessary.

First, the file is parsed and the metadata SEI are stored as they come in from the input, AKA decode order.  
Then, the list of the parsed metadata is reordered to go from decode order to presentation order, so that the JSON has the metadata in the presentation order.
Otherwise, the output JSON would have metadata in the stream's specific decode order, which isn't good.

In correct files, the metadata is expected to be along its corresponding frame according to the presentation timestamp.
So while a frame can be decoded 5th, if it's a B frame it can be displayed 2nd. Thefore the metadata for that frame needs to be the 2nd frame's metadata, not the 5th.

The problem described is that the misauthored files don't have the metadata attached to the right frame (some of the time, because it depends on the encoder's number of B frames).
Rather, they were simply inserted in the **order of the original metadata JSON**, ignoring the order the frames are presented in the final encode.

So when I say the misauthored files shouldn't be reordered, it's because we assume the decode order of the metadata **is** the correct order.
But this is not correct according to the specification, so `--skip-reorder` is optional and specifically for these cases.

**Comment by Audionut** [comment]
You say that the SEI messages should be in display order to match the frames sent to the display, a cursory read seems to suggest that this is correct.

https://community.intel.com/t5/Media-Intel-oneAPI-Video/SEI-are-out-of-order/td-p/1029131
"The SEI message insertion follows the order of encoding. So, if you specify display order and call EncodeFrameAsync, then SEI messages will appear in that order. Basically, you cannot encode in display order and have SEI messages inserted in another order.".

> First, the file is parsed and the metadata SEI are stored as they come in from the input, AKA decode order.

So when the SEI messages are parsed from a source file, a correctly authored file, the SEI messages should already be in display order, not decoded order. So...."the order of the original metadata JSON", from correctly authored files, should already be the correct order.

**Comment by quietvoid** [comment]
> So when the SEI messages are parsed from a source file, a correctly authored file, the SEI messages should already be in display order, not decoded order.

The SEI messages cannot be in display order, because they are contained within access units/frames which are parsed in decode order.

The file is read -> access units are parsed -> SEI message parsed, then the slices for the frame are parsed.  
So every SEI message is "attached" to a specific parsed AU/frame, but the access unit is always encountered/parsed in decode order.
Thus the SEI messages are stored in that same order.

> So...."the order of the original metadata JSON", from correctly authored files, should already be the correct order.

Yes but as we parse (and store while parsing) in decoded order, **the SEI messages' order is only correct specifically for that encoded stream.**
Since we want a JSON that can be used for reencoding/injecting, the SEI messages must be reordered.

> However, when encoding, you are presenting frames in sequential order to the encoder, and the SEI messages should be in the same sequential order.

Exactly, which is why the JSON must be in the same order as the frames sent to the encoder.  
If there was no reordering, they would be sent in the decode order of the original stream they were extracted from.

**Comment by Audionut** [comment]
> The SEI messages cannot be in display order, because they are contained within access units/frames which are parsed in decode order.

Indeed, I was getting myself confused, thanks for the clarification.

> Yes but as we parse (and store while parsing) in decoded order, **the SEI messages' order is only correct specifically for that encoded stream.**
> Since we want a JSON that can be used for reencoding/injecting, the SEI messages must be reordered.

Yes. I'll make the assumption that you can correctly reorder frames from decode order to sequential order.

Cheers again for your time.
